#端口号
server:
  port: 8501
#数据库
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_spzx
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6380
      host: 192.168.200.119
  jackson:
    date-format: yyyy--MM-dd hh:mm:ss
    time-zone: GMT+8
#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
#  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置不拦截的路径
spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /doc.html
      - /webjars/css/**
      - /webjars/js/**
      - /v3/api-docs/**
      - /favicon.ico
# 自定义配置
  minio:
    endpointUrl: http://localhost:9000
    accessKey: minioadmin
    secreKey: minioadmin
    bucketName: spzx
